### ISSUE TITLE
Watching swap files?

### ISSUE THREAD

**Issue by szabgab** [zoffixznet/perl6-Bailador-Dev-AutoRestarter#4]
I've just seen this:

```
Change detected [bin/.app.pl.swp, FileRenamed]. Restarting app
```

It might be better to disregard changes in vim swap files.

**Comment by zoffixznet** [comment]
Thanks, but I have no interest in maintaining Bailador modules. I've de-published this one from the ecosystem.

**Comment by szabgab** [comment]
OK.
Is it ok then to merge your code into the Bailador repository?

**Comment by zoffixznet** [comment]
> Is it ok then to merge your code into the Bailador repository?

Sure. Go ahead.

I also depublished these modules. Feel free to use any of their code, if it's of any use:
https://github.com/zoffixznet/perl6-Bailador-Plugin-Static/
https://github.com/zoffixznet/perl6-Bailador-Plugin-AssetPack-SASS/
https://github.com/zoffixznet/perl6-Bailador-Template-Mojo-Extended/

**Comment by szabgab** [comment]
Thanks

**Comment by szabgab** [comment]
Would you mind transferring these 4 repositories to the Bailador organization?

**Comment by zoffixznet** [comment]
It tells me `You don’t have the permission to create repositories on Bailador`

**Comment by szabgab** [comment]
Create? Did you try to transfer the repos? (GitHub -> Settings -> Transfer)

**Comment by zoffixznet** [comment]
Yup. That still'd create a repo in, say, `Bailador/perl6-Bailador-Dev-AutoRestarter`

**Comment by szabgab** [comment]
Can you try to transfer to me then? User szabgab

**Comment by zoffixznet** [comment]
Done.

**Comment by szabgab** [comment]
Thanks!
